config/routes.rb
Tc2011::Application.routes.draw do
  #######################################################################
  # The Home page
  #######################################################################
  root :controller => "sergeant_shame", :action => "welcome"

  #######################################################################
  # Resources
  #######################################################################
  resources :users
  resources :check_ins
  resources :tasks
  
  #######################################################################
  # Sergeant Shame Application
  #######################################################################
  get 'sergeant_shame/welcome'
  get 'sergeant_shame/logged_in'
end

app/models/check_in.rb
class CheckIn < ActiveRecord::Base
  belongs_to :task
end

app/controllers/check_ins_controller.rb
class CheckInsController < ApplicationController
  # GET /check_ins
  # GET /check_ins.xml
  def index
    @check_ins = CheckIn.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @check_ins }
    end
  end

  # GET /check_ins/1
  # GET /check_ins/1.xml
  def show
    @check_in = CheckIn.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @check_in }
    end
  end

  # GET /check_ins/new
  # GET /check_ins/new.xml
  def new
    @check_in = CheckIn.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @check_in }
    end
  end

  # GET /check_ins/1/edit
  def edit
    @check_in = CheckIn.find(params[:id])
  end

  # POST /check_ins
  # POST /check_ins.xml
  def create
    @check_in = CheckIn.new(params[:check_in])

    respond_to do |format|
      if @check_in.save
        format.html { redirect_to(@check_in, :notice => 'Check in was successfully created.') }
        format.xml  { render :xml => @check_in, :status => :created, :location => @check_in }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @check_in.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /check_ins/1
  # PUT /check_ins/1.xml
  def update
    @check_in = CheckIn.find(params[:id])

    respond_to do |format|
      if @check_in.update_attributes(params[:check_in])
        format.html { redirect_to(@check_in, :notice => 'Check in was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @check_in.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /check_ins/1
  # DELETE /check_ins/1.xml
  def destroy
    @check_in = CheckIn.find(params[:id])
    @check_in.destroy

    respond_to do |format|
      format.html { redirect_to(check_ins_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/check_ins_helper.rb
module CheckInsHelper
end

app/views/check_ins/_check_ins.html.erb
<table>
  <tr>
    <th>Task</th>
    <th>When</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @check_ins.each do |check_in| %>
  <tr>
    <td><%= link_to check_in.task.name, check_in.task %></td>
    <td><%= check_in.created_at %></td>
    <td><%= link_to 'Show', check_in %></td>
    <td><%= link_to 'Edit', edit_check_in_path(check_in) %></td>
    <td><%= link_to 'Destroy', check_in, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/check_ins/_form.html.erb
<%= form_for(@check_in) do |f| %>
  <% if @check_in.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@check_in.errors.count, "error") %> prohibited this check_in from being saved:</h2>

      <ul>
      <% @check_in.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task_id %><br />
    <%= f.text_field :task_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/check_ins/edit.html.erb
<h1>Editing check_in</h1>

<%= render 'form' %>

<%= link_to 'Show', @check_in %> |
<%= link_to 'Back', check_ins_path %>

app/views/check_ins/index.html.erb
<h1>Listing check_ins</h1>

<%= render 'check_ins' %>
<br />

<%= link_to 'New Check in', new_check_in_path %>

app/views/check_ins/new.html.erb
<h1>New check_in</h1>

<%= render 'form' %>

<%= link_to 'Back', check_ins_path %>

app/views/check_ins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Task:</b>
  <%= @check_in.task_id %>
</p>


<%= link_to 'Edit', edit_check_in_path(@check_in) %> |
<%= link_to 'Back', check_ins_path %>